"""add kanban models

Revision ID: 76fb75411365
Revises: fe56fa70289e
Create Date: 2026-05-24 18:45:05.656986

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '76fb75411365'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kanbanproject',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kanbanboard',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['kanbanproject.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kanbancolumn',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('board_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.Enum('TODO', 'IN_PROGRESS', 'REVIEW', 'DONE', name='kanbancolumnkey'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['kanbanboard.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kanbantask',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='kanbantaskpriority'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('repo_full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('branch_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('pr_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('pr_status', sa.Enum('OPEN', 'CLOSED', 'MERGED', name='kanbantaskprstatus'), nullable=True),
    sa.Column('last_commit_sha', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('board_id', sa.Uuid(), nullable=False),
    sa.Column('column_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['kanbanboard.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['column_id'], ['kanbancolumn.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kanbantask')
    op.drop_table('kanbancolumn')
    op.drop_table('kanbanboard')
    op.drop_table('kanbanproject')
    # ### end Alembic commands ###
